package nayttelyrekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import nayttelyrekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.23 20:06:39 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KissaTest {



  // Generated by ComTest BEGIN
  /** testSetSpv194 */
  @Test
  public void testSetSpv194() {    // Kissa: 194
    Kissa kissa = new Kissa(); 
    assertEquals("From: Kissa line: 196", null, kissa.setSpv("22092017")); 
    assertEquals("From: Kissa line: 197", "Syntymäaika väärin", kissa.setSpv("22917")); 
    assertEquals("From: Kissa line: 198", "Syntymäaika väärin", kissa.setSpv("")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetSukupuoli217 */
  @Test
  public void testSetSukupuoli217() {    // Kissa: 217
    Kissa kissa = new Kissa(); 
    assertEquals("From: Kissa line: 219", "Sukupuoli väärin", kissa.setSukupuoli("Sisu")); 
    assertEquals("From: Kissa line: 220", null, kissa.setSukupuoli("uros")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetRekNum259 */
  @Test
  public void testSetRekNum259() {    // Kissa: 259
    Kissa kissa = new Kissa(); 
    assertEquals("From: Kissa line: 261", null, kissa.setRekNum("1822560")); 
    assertEquals("From: Kissa line: 262", "Rekisterinumero väärin", kissa.setRekNum("1822")); 
    assertEquals("From: Kissa line: 263", "Rekisterinumero väärin", kissa.setRekNum("")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi330 */
  @Test
  public void testRekisteroi330() {    // Kissa: 330
    Kissa kissa1 = new Kissa(); 
    assertEquals("From: Kissa line: 332", 0, kissa1.getTunnusNro()); 
    kissa1.rekisteroi(); 
    Kissa kissa2 = new Kissa(); 
    kissa2.rekisteroi(); 
    int n1 = kissa1.getTunnusNro(); 
    int n2 = kissa2.getTunnusNro(); 
    assertEquals("From: Kissa line: 338", n1+1, n2); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnna372 */
  @Test
  public void testAnna372() {    // Kissa: 372
    Kissa kissa = new Kissa(); 
    kissa.parse("3|Electric India      |    FI*Siniidan | Tofu"); 
    assertEquals("From: Kissa line: 375", true, kissa.toString().startsWith("3|Electric India|FI*Siniidan|Tofu|")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString419 */
  @Test
  public void testToString419() {    // Kissa: 419
    Kissa kissa = new Kissa(); 
    kissa.parse(" 3|Electric India|FI*Siniidan|Tofu"); 
    assertEquals("From: Kissa line: 422", true, kissa.toString().startsWith("3|Electric India|FI*Siniidan|Tofu|")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testClone444 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone444() throws CloneNotSupportedException {    // Kissa: 444
    Kissa kissa = new Kissa(); 
    kissa.parse("   3  |  Electric India   | FI*Siniidan"); 
    Kissa kopio = kissa.clone(); 
    assertEquals("From: Kissa line: 449", kissa.toString(), kopio.toString()); 
    kissa.parse("   4  |  Black Halo   | FI*Siniidan"); 
    assertEquals("From: Kissa line: 451", false, kopio.toString().equals(kissa.toString())); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse468 */
  @Test
  public void testParse468() {    // Kissa: 468
    Kissa kissa = new Kissa(); 
    kissa.parse(" 3|Electric India|FI*Siniidan|Tofu"); 
    assertEquals("From: Kissa line: 471", 3, kissa.getTunnusNro()); 
    assertEquals("From: Kissa line: 472", true, kissa.toString().startsWith("3|Electric India|FI*Siniidan|Tofu|")); 
    kissa.rekisteroi(); 
    int n = kissa.getTunnusNro(); 
    kissa.parse(""+(n+20)); 
    kissa.rekisteroi(); 
    assertEquals("From: Kissa line: 478", n+20+1, kissa.getTunnusNro()); 
  } // Generated by ComTest END
}