package nayttelyrekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import nayttelyrekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.23 20:14:50 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TulosTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi87 */
  @Test
  public void testRekisteroi87() {    // Tulos: 87
    Tulos tulos1 = new Tulos(); 
    assertEquals("From: Tulos line: 89", 0, tulos1.getTunnusNro()); 
    tulos1.rekisteroi(); 
    Tulos tulos2 = new Tulos(); 
    tulos2.rekisteroi(); 
    int n1 = tulos1.getTunnusNro(); 
    int n2 = tulos2.getTunnusNro(); 
    assertEquals("From: Tulos line: 95", n1+1, n2); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString131 */
  @Test
  public void testToString131() {    // Tulos: 131
    Tulos tulos = new Tulos(); 
    tulos.parse("3 |1 |1 |CAC |Turpeinen Riikka"); 
    assertEquals("From: Tulos line: 134", true, tulos.toString().startsWith("3|1|1|CAC|")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse246 */
  @Test
  public void testParse246() {    // Tulos: 246
    Tulos tulos = new Tulos(); 
    tulos.parse("3 |2 |1   |CAC |Turpeinen Riikka"); 
    assertEquals("From: Tulos line: 249", 3, tulos.getTunnusNro()); 
    assertEquals("From: Tulos line: 250", true, tulos.toString().startsWith("3|2|1|CAC|")); 
    tulos.rekisteroi(); 
    int n = tulos.getTunnusNro(); 
    tulos.parse(""+(n+20)); 
    tulos.rekisteroi(); 
    assertEquals("From: Tulos line: 256", n+20+1, tulos.getTunnusNro()); 
  } // Generated by ComTest END
}